<?php

/*
 * This file is part of Symfony MailHogger.
 *
 * (c) 2018 ITK Development
 *
 * This source file is subject to the MIT license.
 */

namespace AppBundle\Repository;

/**
 * MailHoggerRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsiteRepository extends \Doctrine\ORM\EntityRepository
{
}
